version: "3"

services: 
    app:
        build: 
            context: .
            dockerfile: './Dockerfile'
        environment:
            PORT: "${PORT}"
        ports:
            - '3000:${PORT}'
        volumes: 
            - '.:/usr/src/'